title: Alder®
email: hello@alder.studio
description: A multidisciplinary graphic design studio connecting art, environment, culture and technology.
baseurl: "/"
url: "alder.world"
image: "/assets/images/alder-social.png"

collections:
  pages:
    output: true
    permalink: /:name/
  projects:
    output: true
    permalink: /:collection/:name/
  stories:
    output: true
    permalink: /:collection/:name/

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

include:
  - _redirects
