title: Alderworld®
email: hello@alder.studio
description: A multi-disciplinary graphic design studio connecting art, enviroment, culutre and technology.
baseurl: "/"
url: "alder.world" 
image: "/assets/images/alder-social.png"

collections:
  pages:
    output: true
    permalink: /:name/
  projects:
    output: true
    permalink: /:collection/:name/
  stories:
    output: true
    permalink: /:collection/:name/    

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed  
    
include:
  - _redirects