title: Alderworld®
email: hello@alder.studio
description: Alder is the Vermont studio of Jasmine Parsia and Chris Norris. We are a multidisciplenary design duo generalizing in graphic design, creative direction, production, web design. 
baseurl: "/"
url: "alder.world" 

collections:
  pages:
    output: true
    permalink: /:name/
  projects:
    output: true
    permalink: /:collection/:name/
  stories:
    output: true
    permalink: /:collection/:name/    

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed  
    
include:
  - _redirects